In [1]:
import numpy as np

In [2]:
label = np.load("/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/labels/700000_1638000_56.npy")

In [3]:
label

array([], dtype=float64)

In [4]:
import os
labels_dir = "/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/labels/"
for file_name in os.listdir(labels_dir):
    file_path = labels_dir + file_name
    label = np.load(file_path)
    print(label)
    print(label.shape)

[]
(0,)
[]
(0,)
[]
(0,)
[]
(0,)
[]
(0,)
[]
(0,)
[[142.  26. 173.  63.]
 [185.  52. 222.  86.]
 [168. 103. 181. 115.]
 [151. 183. 167. 197.]
 [245. 242. 250. 250.]
 [154.  91. 155.  92.]
 [140.  83. 164. 107.]
 [ 48. 185.  66. 204.]
 [ 92. 212.  93. 213.]
 [ 68. 204. 102. 233.]
 [139. 238. 163. 250.]]
(11, 4)
[]
(0,)
[]
(0,)
[]
(0,)
[]
(0,)
[]
(0,)
[[57.  0. 85. 38.]]
(1, 4)
[[173. 123. 236. 180.]]
(1, 4)
[]
(0,)
[]
(0,)
[[ 11.  46.  34.  68.]
 [ 36.  57.  60.  80.]
 [119.  66. 172. 109.]
 [ 24. 110.  66. 149.]]
(4, 4)
[]
(0,)
[[216.  46. 247.  84.]]
(1, 4)
[]
(0,)
[[204.   0. 232.  14.]
 [116.   0. 143.  16.]
 [224.  46. 250.  93.]
 [161.  28. 200. 117.]
 [ 99.  69. 123.  91.]
 [  9. 122.  40. 149.]]
(6, 4)
[]
(0,)
[]
(0,)
[]
(0,)
[]
(0,)
[]
(0,)
[]
(0,)
[]
(0,)
[[ 16.  94.  31. 109.]
 [ 41.  82.  81. 122.]
 [  0. 138.  10. 164.]
 [ 87. 181. 123. 219.]]
(4, 4)
[]
(0,)
[]
(0,)
[[146.  18. 176.  45.]
 [105.  45. 162. 111.]
 [ 64. 113.  65. 114.]
 [ 30.  96. 137. 148.]
 [157. 137. 189. 16

In [5]:
import sys
sys.path.append("../src/")
from run_training_pipeline import download_data, prepare_data, instantiate_lightning_module, instantiate_model, intantiate_dataloader, instantiate_trainer

In [6]:
import yaml
from yaml.loader import SafeLoader

with open("../config.yml") as f:
    config = yaml.load(f, Loader=SafeLoader)
config

{'donnees': {'source train': 'PLEIADES',
  'dataset': 'object_detection',
  'task': 'detection',
  'year': [2022],
  'dep': ['972'],
  'type labeler': 'BDTOPO',
  'buffer size': 10,
  'n channels train': 6,
  'n bands': 3,
  'tile size': 250,
  'augmentation': True},
 'optim': {'loss': 'crossentropy',
  'lr': 0.0001,
  'momentum': 0.9,
  'module': 'fasterrcnn',
  'batch size': 5,
  'max epochs': 100,
  'val prop': 0.2},
 'mlflow': False}

In [7]:
model = instantiate_model(config)
model

FasterRCNNModule(
  (model): FasterRCNN(
    (transform): GeneralizedRCNNTransform(
        Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        Resize(min_size=(800,), max_size=1333, mode='bilinear')
    )
    (backbone): BackboneWithFPN(
      (body): IntermediateLayerGetter(
        (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
        (bn1): FrozenBatchNorm2d(64, eps=0.0)
        (relu): ReLU(inplace=True)
        (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
        (layer1): Sequential(
          (0): Bottleneck(
            (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn1): FrozenBatchNorm2d(64, eps=0.0)
            (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn2): FrozenBatchNorm2d(64, eps=0.0)
            (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
         

In [8]:
from pathlib import Path

list_path_images = []
list_path_labels = []
for name in os.listdir("/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/"):
    npy_name = Path(name).stem + ".npy"
    if os.path.exists("/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/labels/" + npy_name):
        list_path_images.append("/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/" + name)
        list_path_labels.append("/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/labels/" + npy_name)

list_path_images[:10]

['/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/716500_1611000_60.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/720500_1616250_44.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/700375_1638625_19.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/709250_1637625_18.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/726750_1621750_14.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/720500_1625875_4.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/716500_1611250_44.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/720500_1616125_52.jp2',
 '/home/o

In [9]:
import shutil

list_path_images = []
list_path_labels = []
for name in os.listdir("/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/"):
    npy_name = Path(name).stem + ".npy"
    if os.path.exists("/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/labels/" + npy_name):
        shutil.copyfile(
            "/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/images/" + name,
            "/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/" + name
        )
        shutil.copyfile(
            "/home/onyxia/work/detection-habitat-spontane/train_data-PLEIADES-BDTOPO-detection-972-2022/labels/" + npy_name,
            "/home/onyxia/work/detection-habitat-spontane/train_data_notebook/labels/" + npy_name
        )
        list_path_images.append("/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/" + name)
        list_path_labels.append("/home/onyxia/work/detection-habitat-spontane/train_data_notebook/labels/" + npy_name)

list_path_images[:10]

['/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/716500_1611000_60.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/720500_1616250_44.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/700375_1638625_19.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/709250_1637625_18.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/726750_1621750_14.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/720500_1625875_4.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/716500_1611250_44.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/720500_1616125_52.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/720625_1625000_61.jp2',
 '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/716375_1615625_19.jp2']

In [10]:
from run_training_pipeline import intantiate_dataset

full_dataset = intantiate_dataset(
    config, list_path_images, list_path_labels
)

In [11]:
len(full_dataset)

832

In [12]:
import torch

sample_idx = torch.randint(len(full_dataset), size=(1,)).item()
img, label, metadata = full_dataset[sample_idx]

In [13]:
img.shape

torch.Size([3, 250, 250])

In [14]:
model.eval()
model(img.unsqueeze(0))

[{'boxes': tensor([[  0.0000, 248.3640, 250.0000, 250.0000],
          [  0.0000, 246.2846,  24.2098, 248.9398],
          [  0.0000, 240.3943, 250.0000, 250.0000],
          [  0.0000,   0.0000, 250.0000, 250.0000],
          [137.3887,   9.7630, 137.4398,   9.7692],
          [  0.0000, 246.2209, 166.5917, 246.5284],
          [  0.0000, 245.8448, 195.4568, 250.0000],
          [  3.6324, 159.4599,   4.0152, 159.7280],
          [  0.0000, 245.0779, 237.5273, 247.4261],
          [245.3240,  10.2889, 245.7975,  10.4453],
          [229.3717, 171.2635, 231.9134, 171.2684],
          [  0.0000,   0.0000,  55.8536, 250.0000],
          [132.6124,  71.7641, 132.9892,  74.8675],
          [ 69.8743,  51.6542,  70.3104,  51.6963],
          [220.7322, 208.3889, 220.8989, 208.5045],
          [222.3933,  31.7133, 222.7619,  31.8966],
          [197.8434,  16.7023, 197.8468,  16.7129],
          [  0.0000, 244.0163, 250.0000, 244.0422],
          [190.1409, 194.7347, 190.1553, 194.7480],
   

In [15]:
img.shape

torch.Size([3, 250, 250])

In [16]:
label.shape

torch.Size([0, 4])

In [17]:
label

tensor([], size=(0, 4), dtype=torch.int64)

In [18]:
model.model

FasterRCNN(
  (transform): GeneralizedRCNNTransform(
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
      Resize(min_size=(800,), max_size=1333, mode='bilinear')
  )
  (backbone): BackboneWithFPN(
    (body): IntermediateLayerGetter(
      (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
      (bn1): FrozenBatchNorm2d(64, eps=0.0)
      (relu): ReLU(inplace=True)
      (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
      (layer1): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): FrozenBatchNorm2d(64, eps=0.0)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): FrozenBatchNorm2d(64, eps=0.0)
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): FrozenBatchNorm2d(256, eps=0.0)
          (relu): ReLU(

In [19]:
model.train()

targets = []
imgs = []

target = {}
target["boxes"] = label
target["labels"] = torch.ones(len(target["boxes"])).long()
targets.append(target)
imgs.append(img)

In [20]:
targets

[{'boxes': tensor([], size=(0, 4), dtype=torch.int64),
  'labels': tensor([], dtype=torch.int64)}]

In [21]:
loss_dict = model.model(imgs, targets)

In [22]:
loss_dict

{'loss_classifier': tensor(1.0115, grad_fn=<NllLossBackward0>),
 'loss_box_reg': tensor(0., grad_fn=<DivBackward0>),
 'loss_objectness': tensor(45.4679, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>),
 'loss_rpn_box_reg': tensor(0., grad_fn=<DivBackward0>)}

In [23]:
# fasterrcnn takes both images and targets for training, returns
loss = sum(loss for loss in loss_dict.values())
{"loss": loss, "log": loss_dict}

{'loss': tensor(46.4794, grad_fn=<AddBackward0>),
 'log': {'loss_classifier': tensor(1.0115, grad_fn=<NllLossBackward0>),
  'loss_box_reg': tensor(0., grad_fn=<DivBackward0>),
  'loss_objectness': tensor(45.4679, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>),
  'loss_rpn_box_reg': tensor(0., grad_fn=<DivBackward0>)}}

In [24]:
list_output_dir = ["/home/onyxia/work/detection-habitat-spontane/train_data_notebook"]
train_dl, valid_dl, test_dl = intantiate_dataloader(
    config, list_output_dir
)

In [25]:
train_dl

In [28]:
a = next(iter(train_dl))

In [29]:
len(a)

3

In [31]:
a[0].shape

torch.Size([5, 3, 250, 250])

In [32]:
a[1]

[[],
 [(2.0000000949949026,
   28.999999165534973,
   43.0000014603138,
   67.00000166893005),
  (207.0000022649765, 125.0, 250.0, 179.00000512599945),
  (184.00000035762787,
   160.99999845027924,
   216.0000056028366,
   193.00000369548798)],
 [],
 [(116.99999868869781,
   4.000000189989805,
   143.99999380111694,
   35.00000014901161),
  (234.99999940395355, 65.99999964237213, 250.0, 97.99999743700027),
  (78.00000160932541,
   103.00000011920929,
   108.99999737739563,
   129.99999523162842),
  (222.00000286102295, 177.0000010728836, 250.0, 210.999995470047),
  (100.00000149011612,
   181.99999630451202,
   128.9999932050705,
   216.0000056028366),
  (0.0, 64.99999761581421, 8.00000037997961, 90.00000357627869),
  (46.00000008940697, 76.99999958276749, 68.9999982714653, 103.00000011920929),
  (14.000000432133675,
   115.00000208616257,
   35.00000014901161,
   136.99999451637268),
  (0.0, 165.99999368190765, 27.000000700354576, 195.99999487400055),
  (65.99999964237213, 177.0000010

In [33]:
a[2]

[{'pathimage': '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/726000_1621000_56.jp2',
  'pathlabel': '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/labels/726000_1621000_56.npy'},
 {'pathimage': '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/714000_1632000_56.jp2',
  'pathlabel': '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/labels/714000_1632000_56.npy'},
 {'pathimage': '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/726000_1621625_16.jp2',
  'pathlabel': '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/labels/726000_1621625_16.npy'},
 {'pathimage': '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/720125_1616625_17.jp2',
  'pathlabel': '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/labels/720125_1616625_17.npy'},
 {'pathimage': '/home/onyxia/work/detection-habitat-spontane/train_data_notebook/images/717250_16245

Sanity checks

In [37]:
from matplotlib import pyplot as plt
import random
import cv2

hlines = []
for i in range(10):
    vlines = []
    for j in range(5):
        img, bboxes, metadata = full_dataset[random.randint(0, len(full_dataset))]
        for (x, y, xx, yy) in bboxes:
            cv2.rectangle(img, (int(x.item()), int(y.item())), (int(xx.item()), int(yy.item())), (255,255,0), 5)
        vlines.append(img)
    hlines.append(cv2.vconcat(vlines))

final_img = cv2.hconcat(hlines)

fig, ax = plt.subplots(1, 1, figsize=(20, 20))
plt.imshow(final_img)

error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - img is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'img'
>  - img is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'img'


In [38]:
img

tensor([[[ 99.,  98., 101.,  ..., 105., 100., 100.],
         [ 98., 101., 106.,  ..., 101., 101., 101.],
         [100., 101., 103.,  ..., 101., 100., 101.],
         ...,
         [126., 119., 111.,  ..., 104., 103., 105.],
         [136., 138., 131.,  ..., 104., 107., 102.],
         [148., 150., 145.,  ..., 104., 106.,  93.]],

        [[109., 109., 109.,  ..., 113., 108., 110.],
         [109., 109., 114.,  ..., 109., 109., 110.],
         [110., 108., 109.,  ..., 109., 109., 108.],
         ...,
         [128., 125., 117.,  ..., 116., 112., 112.],
         [140., 142., 135.,  ..., 117., 112., 112.],
         [152., 154., 149.,  ..., 112., 109., 113.]],

        [[ 92.,  92., 103.,  ..., 107., 101.,  93.],
         [ 92., 103., 108.,  ...,  96., 102.,  98.],
         [ 95.,  94., 101.,  ...,  92., 101., 103.],
         ...,
         [120., 116., 114.,  ..., 106., 104., 104.],
         [131., 131., 126.,  ..., 104., 106., 108.],
         [143., 145., 140.,  ..., 105., 105.,  99.]]]